### ISSUE TITLE
Práctica De Calidad Metricas

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/practica-5-practica-de-calidad-metricas-con-sonarcloud-balam#1]
[Practica SonarCloud.pdf](https://github.com/SistemasTecTlaxiaco/practica-5-practica-de-calidad-metricas-con-sonarcloud-balam/files/9698720/Practica.SonarCloud.pdf)

**Comment by carlos-chrs** [comment]
calificado 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
